version: '3.8'
services:
  processor-crawl-echelon:
    image: indexer-processor-voting-governance
    container_name: indexer-processor-voting-governance
    volumes:
      - ./config.yaml:/config.yaml
    command: -c ./config.yaml
    restart: no
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
networks:
  default:
    external:
      name: datasource_backend
