# docker build . -t indexer-processor
# docker run -it --network host --mount type=bind,source=/tmp/config.yaml,target=/config.yaml indexer-processor -c /config.yaml
version: '3.8'
services:
  processor-crawl-echelon:
    image: indexer-processor-crawl-echelon
    container_name: processor-crawl-echelon
    volumes:
      - ./config.yaml:/config.yaml
    command: -c ./config.yaml
    restart: no
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
networks:
  default:
    external:
      name: datasource_backend
