name: Deploy Event Mainnet
run-name: ${{ github.actor }} is deploying Event Mainnet
on:
  push:
    branches:
      - "event_mainnet"
jobs:
  deploy:
    runs-on: indexer_mainnet
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          cd rust
          docker compose --project-name event_mainnet -f docker-compose-event-mainnet.yaml down || true
          docker rmi event_mainnet || true
          docker builder prune --all -f
          echo "${{ secrets.ENV_FILE_EVENT_MAINNET }}" >> config.yaml
          docker compose --project-name event_mainnet -f docker-compose-event-mainnet.yaml up -d
          # Remove the last line from the config.yaml file (start_ver)
          sed -i '$ d' config.yaml
          docker image prune -f
