name: Deploy Multisig Mainnet to Indexer VM
run-name: ${{ github.actor }} is deploying Multisig Mainnet to Indexer VM
on:
  push:
    branches:
      - "feat/multisig-mainnet-v2"
jobs:
  deploy:
    runs-on: multisig-mainnet-v2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          cd rust
          docker compose --project-name multisig-mainnet-v2 -f docker-compose-multisig-mainnet-v2.yaml down || true
          docker rmi multisig-mainnet-v2 || true
          docker builder prune --all -f
          echo "${{ secrets.ENV_FILE_MULTISIG_MAINNET_V2 }}" >> config.yaml
          docker compose --project-name multisig-mainnet-v2 -f docker-compose-multisig-mainnet-v2.yaml up -d
          # Remove the last line from the config.yaml file (start_ver)
          sed -i '$ d' config.yaml
          docker image prune -f
