name: Deploy Multisig Testnet to Indexer VM
run-name: ${{ github.actor }} is deploying Multisig Testnet to Indexer VM
on:
  push:
    branches:
      - 'features/implement-multisig-transaction-testnet'
jobs:
  deploy:
    runs-on: multisig-testnet # 236416
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          docker stop multisig-testnet
          docker rm multisig-testnet
          docker rmi multisig-testnet
          docker builder prune --all -f
          cd rust
          echo "${{ secrets.ENV_FILE_MULTISIG_TESTNET }}" >> config.yaml
          docker build . -t multisig-testnet
          docker run --name multisig-testnet -d --restart=always -it --mount type=bind,source=./config.yaml,target=/config.yaml multisig-testnet -c /config.yaml
          # Remove the last line from the config.yaml file (start_ver)
          # sed -i '$ d' config.yaml
          docker image prune -f
