name: Deploy Multisig Testnet to Indexer VM
run-name: ${{ github.actor }} is deploying Multisig Testnet to Indexer VM
on:
  push:
    branches:
      - "features/implement-multisig-transaction-testnet"
jobs:
  deploy:
    runs-on: multisig-testnet # 2658037
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          cd rust
          docker compose --project-name multisig-testnet -f docker-compose-multisig-testnet.yaml down || true
          docker rmi multisig-testnet || true
          docker builder prune --all -f
          echo "${{ secrets.ENV_FILE_MULTISIG_TESTNET }}" >> config.yaml
          docker compose --project-name multisig-testnet -f docker-compose-multisig-testnet.yaml up -d
          # Remove the last line from the config.yaml file (start_ver)
          sed -i '$ d' config.yaml
          docker image prune -f
